# hydra.job.chdir: false
hydra:
  searchpath:
    # see https://hydra.cc/docs/advanced/search_path/
    - file://../cfg

# run
headless: false  # default to headless to avoid GLX errors on servers without a display

sim: ${task.sim}
env: ${task.env}

total_frames: 500_000_000
max_iters: -1
eval_interval: 500
save_interval: 500

# Evaluation rollout length (steps). Higher = more accurate but slower and higher memory.
eval_max_steps: 1024
# If you save videos, keep this smaller to avoid huge files.
eval_video_max_steps: 256
record_video: false

seed: 0
# resume_checkpoint: /home/csj/orp/models/orp6.1.pt
resume_checkpoint: null  # set to a .pt path to continue training, keep null to start from scratch

viewer:
  resolution: [960, 720]
  eye: [0., -2, 1]
  lookat: [0., 1., 0.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity:
  project: orp-scripts
  mode: online # set to 'disabled' when debugging locally
  run_id:
  monitor_gym: True
  tags:

defaults:
  - task: train_env_goal
  - algo: ppo
  - _self_
